//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoteCreate", Namespace="http://tempuri.org/")]
    public partial class NoteCreate : object
    {
        
        private string TitleField;
        
        private string ContentField;
        
        private int CategoryEntityIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int CategoryEntityId
        {
            get
            {
                return this.CategoryEntityIdField;
            }
            set
            {
                this.CategoryEntityIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoteEdit", Namespace="http://tempuri.org/")]
    public partial class NoteEdit : object
    {
        
        private int IdField;
        
        private string TitleField;
        
        private string ContentField;
        
        private int CategoryEntityIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CategoryEntityId
        {
            get
            {
                return this.CategoryEntityIdField;
            }
            set
            {
                this.CategoryEntityIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoteListItem", Namespace="http://tempuri.org/")]
    public partial class NoteListItem : object
    {
        
        private int IdField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoteDetail", Namespace="http://tempuri.org/")]
    public partial class NoteDetail : object
    {
        
        private int IdField;
        
        private string TitleField;
        
        private string ContentField;
        
        private NotesReference.CategoryListItem CategoryField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public NotesReference.CategoryListItem Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryListItem", Namespace="http://tempuri.org/")]
    public partial class CategoryListItem : object
    {
        
        private int IdField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NotesReference.INoteService")]
    public interface INoteService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoteService/AddNote", ReplyAction="*")]
        System.Threading.Tasks.Task<NotesReference.AddNoteResponse> AddNoteAsync(NotesReference.AddNoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoteService/EditNote", ReplyAction="*")]
        System.Threading.Tasks.Task<NotesReference.EditNoteResponse> EditNoteAsync(NotesReference.EditNoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoteService/DeleteNote", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteNoteAsync(int noteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoteService/GetNotes", ReplyAction="*")]
        System.Threading.Tasks.Task<NotesReference.NoteListItem[]> GetNotesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoteService/GetNote", ReplyAction="*")]
        System.Threading.Tasks.Task<NotesReference.GetNoteResponse> GetNoteAsync(NotesReference.GetNoteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNoteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNote", Namespace="http://tempuri.org/", Order=0)]
        public NotesReference.AddNoteRequestBody Body;
        
        public AddNoteRequest()
        {
        }
        
        public AddNoteRequest(NotesReference.AddNoteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNoteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NotesReference.NoteCreate note;
        
        public AddNoteRequestBody()
        {
        }
        
        public AddNoteRequestBody(NotesReference.NoteCreate note)
        {
            this.note = note;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNoteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNoteResponse", Namespace="http://tempuri.org/", Order=0)]
        public NotesReference.AddNoteResponseBody Body;
        
        public AddNoteResponse()
        {
        }
        
        public AddNoteResponse(NotesReference.AddNoteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNoteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddNoteResult;
        
        public AddNoteResponseBody()
        {
        }
        
        public AddNoteResponseBody(bool AddNoteResult)
        {
            this.AddNoteResult = AddNoteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditNoteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditNote", Namespace="http://tempuri.org/", Order=0)]
        public NotesReference.EditNoteRequestBody Body;
        
        public EditNoteRequest()
        {
        }
        
        public EditNoteRequest(NotesReference.EditNoteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditNoteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NotesReference.NoteEdit note;
        
        public EditNoteRequestBody()
        {
        }
        
        public EditNoteRequestBody(NotesReference.NoteEdit note)
        {
            this.note = note;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditNoteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditNoteResponse", Namespace="http://tempuri.org/", Order=0)]
        public NotesReference.EditNoteResponseBody Body;
        
        public EditNoteResponse()
        {
        }
        
        public EditNoteResponse(NotesReference.EditNoteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditNoteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EditNoteResult;
        
        public EditNoteResponseBody()
        {
        }
        
        public EditNoteResponseBody(bool EditNoteResult)
        {
            this.EditNoteResult = EditNoteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNoteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNote", Namespace="http://tempuri.org/", Order=0)]
        public NotesReference.GetNoteRequestBody Body;
        
        public GetNoteRequest()
        {
        }
        
        public GetNoteRequest(NotesReference.GetNoteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNoteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetNoteRequestBody()
        {
        }
        
        public GetNoteRequestBody(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNoteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNoteResponse", Namespace="http://tempuri.org/", Order=0)]
        public NotesReference.GetNoteResponseBody Body;
        
        public GetNoteResponse()
        {
        }
        
        public GetNoteResponse(NotesReference.GetNoteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNoteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NotesReference.NoteDetail GetNoteResult;
        
        public GetNoteResponseBody()
        {
        }
        
        public GetNoteResponseBody(NotesReference.NoteDetail GetNoteResult)
        {
            this.GetNoteResult = GetNoteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface INoteServiceChannel : NotesReference.INoteService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class NoteServiceClient : System.ServiceModel.ClientBase<NotesReference.INoteService>, NotesReference.INoteService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NoteServiceClient() : 
                base(NoteServiceClient.GetDefaultBinding(), NoteServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_INoteService_soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NoteServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(NoteServiceClient.GetBindingForEndpoint(endpointConfiguration), NoteServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NoteServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NoteServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NoteServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NoteServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NoteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotesReference.AddNoteResponse> NotesReference.INoteService.AddNoteAsync(NotesReference.AddNoteRequest request)
        {
            return base.Channel.AddNoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotesReference.AddNoteResponse> AddNoteAsync(NotesReference.NoteCreate note)
        {
            NotesReference.AddNoteRequest inValue = new NotesReference.AddNoteRequest();
            inValue.Body = new NotesReference.AddNoteRequestBody();
            inValue.Body.note = note;
            return ((NotesReference.INoteService)(this)).AddNoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotesReference.EditNoteResponse> NotesReference.INoteService.EditNoteAsync(NotesReference.EditNoteRequest request)
        {
            return base.Channel.EditNoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotesReference.EditNoteResponse> EditNoteAsync(NotesReference.NoteEdit note)
        {
            NotesReference.EditNoteRequest inValue = new NotesReference.EditNoteRequest();
            inValue.Body = new NotesReference.EditNoteRequestBody();
            inValue.Body.note = note;
            return ((NotesReference.INoteService)(this)).EditNoteAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteNoteAsync(int noteId)
        {
            return base.Channel.DeleteNoteAsync(noteId);
        }
        
        public System.Threading.Tasks.Task<NotesReference.NoteListItem[]> GetNotesAsync()
        {
            return base.Channel.GetNotesAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotesReference.GetNoteResponse> NotesReference.INoteService.GetNoteAsync(NotesReference.GetNoteRequest request)
        {
            return base.Channel.GetNoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotesReference.GetNoteResponse> GetNoteAsync(int id)
        {
            NotesReference.GetNoteRequest inValue = new NotesReference.GetNoteRequest();
            inValue.Body = new NotesReference.GetNoteRequestBody();
            inValue.Body.id = id;
            return ((NotesReference.INoteService)(this)).GetNoteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INoteService_soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INoteService_soap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7299/ElevenNoteNotes.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return NoteServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_INoteService_soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return NoteServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_INoteService_soap);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_INoteService_soap,
        }
    }
}
