//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryCreate", Namespace="http://tempuri.org/")]
    public partial class CategoryCreate : object
    {
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryEdit", Namespace="http://tempuri.org/")]
    public partial class CategoryEdit : object
    {
        
        private int IdField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryListItem", Namespace="http://tempuri.org/")]
    public partial class CategoryListItem : object
    {
        
        private int IdField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryDetail", Namespace="http://tempuri.org/")]
    public partial class CategoryDetail : object
    {
        
        private int IdField;
        
        private string TitleField;
        
        private ServiceReference.NoteListItem[] NotesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ServiceReference.NoteListItem[] Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoteListItem", Namespace="http://tempuri.org/")]
    public partial class NoteListItem : object
    {
        
        private int IdField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ICategoryService")]
    public interface ICategoryService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryService/AddCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.AddCategoryResponse> AddCategoryAsync(ServiceReference.AddCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryService/EditCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.EditCategoryResponse> EditCategoryAsync(ServiceReference.EditCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryService/DeleteCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteCategoryAsync(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryService/GetCategories", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.CategoryListItem[]> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryService/GetCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.GetCategoryResponse> GetCategoryAsync(ServiceReference.GetCategoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCategoryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCategory", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference.AddCategoryRequestBody Body;
        
        public AddCategoryRequest()
        {
        }
        
        public AddCategoryRequest(ServiceReference.AddCategoryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCategoryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.CategoryCreate category;
        
        public AddCategoryRequestBody()
        {
        }
        
        public AddCategoryRequestBody(ServiceReference.CategoryCreate category)
        {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCategoryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference.AddCategoryResponseBody Body;
        
        public AddCategoryResponse()
        {
        }
        
        public AddCategoryResponse(ServiceReference.AddCategoryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCategoryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddCategoryResult;
        
        public AddCategoryResponseBody()
        {
        }
        
        public AddCategoryResponseBody(bool AddCategoryResult)
        {
            this.AddCategoryResult = AddCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditCategoryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditCategory", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference.EditCategoryRequestBody Body;
        
        public EditCategoryRequest()
        {
        }
        
        public EditCategoryRequest(ServiceReference.EditCategoryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditCategoryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.CategoryEdit category;
        
        public EditCategoryRequestBody()
        {
        }
        
        public EditCategoryRequestBody(ServiceReference.CategoryEdit category)
        {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditCategoryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference.EditCategoryResponseBody Body;
        
        public EditCategoryResponse()
        {
        }
        
        public EditCategoryResponse(ServiceReference.EditCategoryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditCategoryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EditCategoryResult;
        
        public EditCategoryResponseBody()
        {
        }
        
        public EditCategoryResponseBody(bool EditCategoryResult)
        {
            this.EditCategoryResult = EditCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategory", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference.GetCategoryRequestBody Body;
        
        public GetCategoryRequest()
        {
        }
        
        public GetCategoryRequest(ServiceReference.GetCategoryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCategoryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetCategoryRequestBody()
        {
        }
        
        public GetCategoryRequestBody(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference.GetCategoryResponseBody Body;
        
        public GetCategoryResponse()
        {
        }
        
        public GetCategoryResponse(ServiceReference.GetCategoryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCategoryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.CategoryDetail GetCategoryResult;
        
        public GetCategoryResponseBody()
        {
        }
        
        public GetCategoryResponseBody(ServiceReference.CategoryDetail GetCategoryResult)
        {
            this.GetCategoryResult = GetCategoryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ICategoryServiceChannel : ServiceReference.ICategoryService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class CategoryServiceClient : System.ServiceModel.ClientBase<ServiceReference.ICategoryService>, ServiceReference.ICategoryService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CategoryServiceClient() : 
                base(CategoryServiceClient.GetDefaultBinding(), CategoryServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICategoryService_soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CategoryServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CategoryServiceClient.GetBindingForEndpoint(endpointConfiguration), CategoryServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CategoryServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CategoryServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CategoryServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CategoryServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CategoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.AddCategoryResponse> ServiceReference.ICategoryService.AddCategoryAsync(ServiceReference.AddCategoryRequest request)
        {
            return base.Channel.AddCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.AddCategoryResponse> AddCategoryAsync(ServiceReference.CategoryCreate category)
        {
            ServiceReference.AddCategoryRequest inValue = new ServiceReference.AddCategoryRequest();
            inValue.Body = new ServiceReference.AddCategoryRequestBody();
            inValue.Body.category = category;
            return ((ServiceReference.ICategoryService)(this)).AddCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.EditCategoryResponse> ServiceReference.ICategoryService.EditCategoryAsync(ServiceReference.EditCategoryRequest request)
        {
            return base.Channel.EditCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.EditCategoryResponse> EditCategoryAsync(ServiceReference.CategoryEdit category)
        {
            ServiceReference.EditCategoryRequest inValue = new ServiceReference.EditCategoryRequest();
            inValue.Body = new ServiceReference.EditCategoryRequestBody();
            inValue.Body.category = category;
            return ((ServiceReference.ICategoryService)(this)).EditCategoryAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCategoryAsync(int categoryId)
        {
            return base.Channel.DeleteCategoryAsync(categoryId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.CategoryListItem[]> GetCategoriesAsync()
        {
            return base.Channel.GetCategoriesAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetCategoryResponse> ServiceReference.ICategoryService.GetCategoryAsync(ServiceReference.GetCategoryRequest request)
        {
            return base.Channel.GetCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetCategoryResponse> GetCategoryAsync(int id)
        {
            ServiceReference.GetCategoryRequest inValue = new ServiceReference.GetCategoryRequest();
            inValue.Body = new ServiceReference.GetCategoryRequestBody();
            inValue.Body.id = id;
            return ((ServiceReference.ICategoryService)(this)).GetCategoryAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICategoryService_soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICategoryService_soap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7299/ElevenNoteCategories.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CategoryServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICategoryService_soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CategoryServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICategoryService_soap);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICategoryService_soap,
        }
    }
}
